[package]
name = "peer_protocol"
version = "0.1.0"

[dependencies]
starknet = "2.8.2"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.17.0" }
pragma_lib = { git = "https://github.com/astraly-labs/pragma-lib" }
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git" }

[dev-dependencies]
assert_macros = "2.8.2"
snforge_std = "0.31.0"

[[target.starknet-contract]]
casm = true
sierra = true

[scripts]
test = "snforge test"
